### ISSUE TITLE
gradle sync failed after I update AGP from 3.5.x to 3.6.0

### ISSUE THREAD

**Issue by matsujun** [DeployGate/gradle-deploygate-plugin#101]
This is call stack.
```
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'property(interface org.gradle.api.file.Directory, property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, <output dir path>)))' with class 'org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar' to class 'java.io.File'
	at com.deploygate.gradle.plugins.artifacts.PackageAppTaskCompat.getApkInfo(PackageAppTaskCompat.groovy:17)
	at com.deploygate.gradle.plugins.artifacts.PackageAppTaskCompat$getApkInfo.call(Unknown Source)
	at com.deploygate.gradle.plugins.tasks.factory.AGPBasedUploadApkTaskFactory$_registerUploadApkTask_closure1.doCall(AGPBasedUploadApkTaskFactory.groovy:36)
	at com.sun.proxy.$Proxy72.execute(Unknown Source)
	at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:42)
	at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:42)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
	at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:264)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:112)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:258)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:942)
	... 170 more
```

* Android Gradle Plugin : 3.6.0
* We are defining both flavor and build types

Sorry, I could not find minimum condition to reproduce this error...
I tried to create template app from Android Studio, and just add deploygate plugin, and add both flavor and build types. But this issue is not possible to reproduce...

Maybe, this is similar issue
https://github.com/bugsnag/bugsnag-android-gradle-plugin/pull/122

**Comment by matsujun** [comment]
I'm sorry.
It was fixed 2.1.0...
